name: Python Flask Application CI/CD

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/sup-python@v5
        with:
          python-version: '3.8'

      - name: Make script executable
        run: chmod +x ./flaskapp/st.sh

      - name: Install dependencies with correct versions
        run: |
          python -m pip install --upgrade pip
          # Сначала устанавливаем совместимый protobuf
          pip install "protobuf<3.20" --force-reinstall
          # Затем TensorFlow и остальные зависимости
          pip install tensorflow==2.10.0 keras==2.10.0
          pip install flask gunicorn requests flask-bootstrap flask-wtf pillow
          
      - name: Verify installations
        run: |
          pip list
          python -c "import tensorflow as tf; print('TF Version:', tf.__version__)"
          python -c "import protobuf; print('Protobuf Version:', protobuf.__version__)"

      - name: Run application
        working-directory: ./flaskapp
        run: ./st.sh