name: Python Flask Application CI/CD

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Шаг 3: Даем права на выполнение скрипта
      - name: Make script executable
        run: chmod +x ./flaskapp/st.sh

      # Шаг 4: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install protobuf==3.20.1
          pip install flask gunicorn requests flask-bootstrap flask-wtf pillow
          pip install tensorflow==2.12.0 keras

      # Шаг 5: Проверка установленных пакетов (для отладки)
      - name: Verify installations
        run: |
          pip list
          python -c "import tensorflow as tf; print(tf.__version__)"

      # Шаг 6: Запуск приложения
      - name: Run application
        working-directory: ./flaskapp
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: ./st.sh
