name: Python CI

on: [push, pull_request]  # Запуск при push или PR

jobs:
  test:
    runs-on: ubuntu-latest   # ОС для запуска

    steps:
      - uses: actions/checkout@v4  # Клонирует репозиторий

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Автовыбор последней версии Python 3

      - name: Install dependencies
        run: pip install flask   # Установка Flask

      - name: Run the app
        run: python ./flaskapp/some_app.py  # Запуск приложения